### PR TITLE
Merge change to 15.x branch

### PR DESCRIPTION
**Pull request by azat**
Looks like #8 forgot to merge this to 15.x and simply switch the HEAD in the submodules, let's do this to make the HEAD of the `Clickhoues/release/15.x` up to date (plus I have one more patch - #9)

Cc: @rschu1ze 
Cc: @hanfei1991

### CODE REVIEW

**Comment by rschu1ze** [comment]
Nice catch. The PR is good to go once https://github.com/ClickHouse/llvm-project/pull/9#issuecomment-1473875048 is clarified ... btw., I couldn't find a corresponding PR in the ClickHouse repo that updates the llvm-project submodule?

**Comment by azat** [comment]
>The PR is good to go once https://github.com/ClickHouse/llvm-project/pull/9#issuecomment-1473875048 is clarified ... 

It does not contains anything from #9, so I think it is safe to merge it now.

Plus, I want to rebase on top of that changes (since I want to create a draft PR in ClickHouse that will include not only #9 but also #8)

> I couldn't find a corresponding PR in the ClickHouse repo that updates the llvm-project submodule?

It should be https://github.com/ClickHouse/ClickHouse/pull/46600

**Comment by rschu1ze** [comment]
>> I couldn't find a corresponding PR in the ClickHouse repo that updates the llvm-project submodule?
> It should be https://github.com/ClickHouse/ClickHouse/pull/46600

What I meant was whether this PR has an equivalent in the main repo already. But nevermind, here it is: https://github.com/ClickHouse/ClickHouse/pull/47719

**Comment by azat** [comment]
> What I meant was whether this PR has an equivalent in the main repo already.

Well, it can't be done until this MR merged.

>https://github.com/ClickHouse/ClickHouse/pull/47719

Yep, thanks!

**Pull request merged**
